// Auto-generated by split.py — do not edit directly
// Depends on data.js being loaded first (window.INITIAL_DATA)

if (!window.INITIAL_DATA || !Array.isArray(window.INITIAL_DATA)) {
    var listEl = document.getElementById('list');
    if (listEl) listEl.innerHTML =
        '<div style="padding:20px;color:#ef4444;">Error: data.js failed to load. Try a hard refresh (Ctrl+Shift+R).</div>';
    throw new Error('window.INITIAL_DATA not set — data.js may have failed to load');
}

    // --- MAPPING (jobTitle -> Name | name -> Company) ---
    const contacts = window.INITIAL_DATA.map((c, i) => ({
        id:             c.id || i,
        person:         c.full_name || ((c.first_name||'') + ' ' + (c.last_name||'')).trim() || 'Unknown',
        entity:         c.company || '',
        position:       c.position || '',
        linkedin:       c.linkedin_url || '',
        email:          c.email || '',
        email2:         c.email2 || '',
        email3:         c.email3 || '',
        phone:          c.phone || '',
        whatsapp:       c.whatsapp || '',
        telegram:       c.telegram || '',
        signal:         c.signal || '',
        wechat:         c.wechat || '',
        twitter:        c.twitter || '',
        website1:       c.website1 || '',
        website2:       c.website2 || '',
        website3:       c.website3 || '',
        birthday:       c.birthday || '',
        connected_on:   c.connected_on || '',
        sector_tags:    (c.sector_tags  || []).join(', '),
        custom_tags:    (c.custom_tags  || []).join(', '),
        seniority:      c.seniority || '',
        relevance_score: c.relevance_score || 0,
        priority:       c.priority || '',
        status:         c.status || '',
        // "About" = manually stored about field (populated via LOCAL_BRIDGE)
        about:          c.about || '',
        // Message history from notes array
        notes:          (c.notes || []).map(n => n.text || '').filter(Boolean)
    }));

    // ══════════════════════════════════════════════════════
    //  NEW CONTACT PERSISTENCE — localStorage delta
    //  Stored in localStorage["cgs_new_contacts"] as the
    //  internal mapped schema (same shape as contacts[]).
    //  Survives reload on this device. Export JSON to share.
    // ══════════════════════════════════════════════════════
    function loadNewContacts() {
        try { return JSON.parse(localStorage.getItem('cgs_new_contacts') || '[]'); } catch(e) { return []; }
    }
    function persistNewContact(c) {
        const arr = loadNewContacts().filter(x => x.id !== c.id); // no duplicates
        arr.unshift(c);
        localStorage.setItem('cgs_new_contacts', JSON.stringify(arr));
    }
    function deletePersistedContact(id) {
        const arr = loadNewContacts().filter(c => c.id !== id);
        localStorage.setItem('cgs_new_contacts', JSON.stringify(arr));
    }

    // Merge any previously saved new contacts into the live array (prepend = top of list)
    loadNewContacts().forEach(c => contacts.unshift(c));

    // ══════════════════════════════════════════════════════
    //  PROJECTS — localStorage-backed
    // ══════════════════════════════════════════════════════
    function loadProjects() {
        try { return JSON.parse(localStorage.getItem('cgs_projects') || '[]'); } catch(e) { return []; }
    }
    function saveProjects(arr) {
        localStorage.setItem('cgs_projects', JSON.stringify(arr));
    }
    function nextProjectId(arr) {
        return arr.reduce((m,p) => Math.max(m, p.id||0), 0) + 1;
    }

    function createProject(name, description, status) {
        const arr = loadProjects();
        const p = {
            id: nextProjectId(arr),
            name: name.trim(),
            description: (description||'').trim(),
            status: status || 'Active',
            created: new Date().toISOString().slice(0,10),
            contactIds: []
        };
        arr.push(p);
        saveProjects(arr);
        return p;
    }

    function getProject(id) {
        return loadProjects().find(p => p.id === id);
    }

    function addContactToProject(projectId, contactId) {
        const arr = loadProjects();
        const p = arr.find(p => p.id === projectId);
        if (!p) return;
        if (!p.contactIds.includes(contactId)) p.contactIds.push(contactId);
        saveProjects(arr);
    }

    function removeContactFromProject(projectId, contactId) {
        const arr = loadProjects();
        const p = arr.find(p => p.id === projectId);
        if (!p) return;
        p.contactIds = p.contactIds.filter(id => id !== contactId);
        saveProjects(arr);
    }

    function deleteProject(projectId) {
        const arr = loadProjects().filter(p => p.id !== projectId);
        saveProjects(arr);
    }

    function escHtml(s) {
        return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
    }

    function showToast(msg) {
        const t = document.createElement('div');
        t.style.cssText = 'position:fixed;bottom:24px;left:50%;transform:translateX(-50%);background:#1e293b;border:1px solid #334155;color:#f1f5f9;padding:10px 20px;border-radius:8px;font-size:0.85rem;z-index:9999;box-shadow:0 4px 20px rgba(0,0,0,.4);';
        t.textContent = msg;
        document.body.appendChild(t);
        setTimeout(() => t.remove(), 2500);
    }

    function showAddToProjectMenu(contactId, btn) {
        const existing = document.getElementById('atp-menu');
        if (existing) { existing.remove(); return; }
        const projects = loadProjects();
        const menu = document.createElement('div');
        menu.id = 'atp-menu';
        menu.style.cssText = 'position:absolute;background:#1e293b;border:1px solid #334155;border-radius:8px;padding:8px;z-index:3000;min-width:200px;box-shadow:0 8px 30px rgba(0,0,0,.5);';
        if (!projects.length) {
            menu.innerHTML = '<div style="color:#64748b;font-size:0.8rem;padding:6px 8px;">No projects yet — create one first.</div>';
        } else {
            menu.innerHTML = projects.map(p => `
                <div onclick="addContactToProject(${p.id},${contactId});document.getElementById('atp-menu').remove();showToast('Added to '+${JSON.stringify(p.name)});"
                     style="padding:8px 12px;border-radius:6px;cursor:pointer;font-size:0.85rem;color:#f1f5f9;" onmouseover="this.style.background='#334155'" onmouseout="this.style.background=''">${escHtml(p.name)}
                     <span style="font-size:0.7rem;color:#64748b;margin-left:4px;">${p.contactIds.includes(contactId)?'✓':''}</span>
                </div>`).join('');
        }
        document.body.appendChild(menu);
        const rect = btn.getBoundingClientRect();
        menu.style.top = (rect.bottom + window.scrollY + 4) + 'px';
        menu.style.left = (rect.left + window.scrollX) + 'px';
        document.addEventListener('click', function close(e) {
            if (!menu.contains(e.target) && e.target !== btn) { menu.remove(); document.removeEventListener('click', close); }
        });
    }

    function openProjectsPanel() {
        const existing = document.getElementById('projects-panel-overlay');
        if (existing) { existing.remove(); return; }

        const ov = document.createElement('div');
        ov.id = 'projects-panel-overlay';
        ov.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,0.65);z-index:2000;display:flex;align-items:flex-start;justify-content:center;padding:40px 20px;overflow-y:auto;';
        ov.innerHTML = buildProjectsPanelHTML();
        document.body.appendChild(ov);
        ov.addEventListener('click', e => { if(e.target===ov) closeProjectsPanel(); });
    }

    function closeProjectsPanel() {
        const el = document.getElementById('projects-panel-overlay');
        if (el) el.remove();
    }

    function buildProjectsPanelHTML() {
        const projects = loadProjects();
        const statusColor = { Active:'#22c55e', Pipeline:'#f59e0b', Closed:'#64748b' };

        let rows = '';
        if (!projects.length) {
            rows = '<div style="color:#64748b;text-align:center;padding:40px 0;">No projects yet. Create one above.</div>';
        } else {
            projects.forEach(p => {
                const col = statusColor[p.status] || '#64748b';
                rows += `
                <div style="background:#0f172a;border:1px solid #334155;border-radius:8px;padding:16px 20px;margin-bottom:10px;cursor:pointer;"
                     onclick="openProjectDetail(${p.id})">
                  <div style="display:flex;justify-content:space-between;align-items:center;">
                    <strong style="font-size:0.95rem;color:#f1f5f9;">${escHtml(p.name)}</strong>
                    <span style="font-size:0.7rem;padding:2px 8px;border-radius:10px;background:${col}22;color:${col};border:1px solid ${col}55;">${p.status}</span>
                  </div>
                  ${p.description ? `<div style="font-size:0.8rem;color:#64748b;margin-top:4px;">${escHtml(p.description)}</div>` : ''}
                  <div style="font-size:0.75rem;color:#475569;margin-top:6px;">${p.contactIds.length} contact${p.contactIds.length!==1?'s':''} · Created ${p.created}</div>
                </div>`;
            });
        }

        return `
        <div style="background:#1e293b;border:1px solid #334155;border-radius:14px;width:100%;max-width:680px;padding:32px;position:relative;color:#f1f5f9;font-family:'Segoe UI',sans-serif;">
          <button onclick="closeProjectsPanel()" style="position:absolute;top:16px;right:18px;background:none;border:none;color:#64748b;font-size:1.3rem;cursor:pointer;">✕</button>
          <h2 style="margin:0 0 4px;font-size:1.2rem;">Projects</h2>
          <p style="margin:0 0 20px;font-size:0.8rem;color:#64748b;">Organise contacts into projects or campaigns.</p>

          <!-- New project form -->
          <div style="background:#0f172a;border:1px solid #334155;border-radius:8px;padding:16px;margin-bottom:20px;">
            <div style="font-size:0.75rem;color:#94a3b8;font-weight:600;text-transform:uppercase;letter-spacing:.6px;margin-bottom:12px;">New Project</div>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px;">
              <input id="np-name" placeholder="Project name *" style="padding:9px 12px;border-radius:6px;border:1px solid #334155;background:#1e293b;color:#f1f5f9;font-size:0.85rem;outline:none;grid-column:1/-1;">
              <input id="np-desc" placeholder="Description (optional)" style="padding:9px 12px;border-radius:6px;border:1px solid #334155;background:#1e293b;color:#f1f5f9;font-size:0.85rem;outline:none;grid-column:1/-1;">
              <select id="np-status" style="padding:9px 12px;border-radius:6px;border:1px solid #334155;background:#1e293b;color:#f1f5f9;font-size:0.85rem;outline:none;">
                <option value="Active">Active</option>
                <option value="Pipeline">Pipeline</option>
                <option value="Closed">Closed</option>
              </select>
              <button onclick="submitNewProject()" style="padding:9px 16px;border-radius:6px;border:none;background:#3b82f6;color:#fff;font-weight:600;font-size:0.85rem;cursor:pointer;">+ Create Project</button>
            </div>
          </div>

          <!-- Project list -->
          <div id="projects-list">${rows}</div>
        </div>`;
    }

    function submitNewProject() {
        const name = (document.getElementById('np-name').value||'').trim();
        if (!name) { document.getElementById('np-name').style.borderColor='#ef4444'; return; }
        const desc   = document.getElementById('np-desc').value || '';
        const status = document.getElementById('np-status').value || 'Active';
        createProject(name, desc, status);
        // Refresh the panel
        closeProjectsPanel();
        openProjectsPanel();
    }

    function openProjectDetail(projectId) {
        closeProjectsPanel();
        const p = getProject(projectId);
        if (!p) return;

        const ov = document.createElement('div');
        ov.id = 'project-detail-overlay';
        ov.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,0.65);z-index:2000;display:flex;align-items:flex-start;justify-content:center;padding:40px 20px;overflow-y:auto;';
        ov.innerHTML = buildProjectDetailHTML(p);
        document.body.appendChild(ov);
        ov.addEventListener('click', e => { if(e.target===ov) closeProjectDetail(); });
    }

    function closeProjectDetail() {
        const el = document.getElementById('project-detail-overlay');
        if (el) el.remove();
    }

    function buildProjectDetailHTML(p) {
        const statusColor = { Active:'#22c55e', Pipeline:'#f59e0b', Closed:'#64748b' };
        const col = statusColor[p.status] || '#64748b';

        const projectContacts = contacts.filter(c => p.contactIds.includes(c.id));

        let rows = '';
        if (!projectContacts.length) {
            rows = '<div style="color:#64748b;text-align:center;padding:30px 0;">No contacts in this project. Use "Add Contacts" below.</div>';
        } else {
            projectContacts.forEach(c => {
                rows += `
                <div style="display:flex;align-items:center;justify-content:space-between;padding:10px 14px;background:#0f172a;border:1px solid #334155;border-radius:6px;margin-bottom:6px;">
                  <div style="cursor:pointer;" onclick="closeProjectDetail();view(${c.id});">
                    <strong style="font-size:0.88rem;color:#f1f5f9;">${escHtml(c.person)}</strong>
                    <span style="color:#64748b;font-size:0.78rem;margin-left:8px;">${escHtml(c.entity)}</span>
                    ${c.position ? `<div style="font-size:0.75rem;color:#475569;">${escHtml(c.position)}</div>` : ''}
                  </div>
                  <button onclick="removeContactFromProject(${p.id},${c.id});refreshProjectDetail(${p.id});"
                          style="background:none;border:1px solid #334155;border-radius:4px;color:#64748b;font-size:0.75rem;padding:3px 8px;cursor:pointer;">✕ Remove</button>
                </div>`;
            });
        }

        return `
        <div style="background:#1e293b;border:1px solid #334155;border-radius:14px;width:100%;max-width:680px;padding:32px;position:relative;color:#f1f5f9;font-family:'Segoe UI',sans-serif;">
          <button onclick="closeProjectDetail();openProjectsPanel();" style="position:absolute;top:16px;right:18px;background:none;border:none;color:#64748b;font-size:0.8rem;cursor:pointer;">← Back</button>
          <div style="display:flex;align-items:center;gap:12px;margin-bottom:6px;">
            <h2 style="margin:0;font-size:1.2rem;">${escHtml(p.name)}</h2>
            <span style="font-size:0.7rem;padding:2px 8px;border-radius:10px;background:${col}22;color:${col};border:1px solid ${col}55;">${p.status}</span>
          </div>
          ${p.description ? `<p style="margin:0 0 6px;font-size:0.8rem;color:#64748b;">${escHtml(p.description)}</p>` : ''}
          <p style="margin:0 0 20px;font-size:0.75rem;color:#475569;">Created ${p.created} · ${p.contactIds.length} contact${p.contactIds.length!==1?'s':''}</p>

          <!-- Add contacts search -->
          <div style="margin-bottom:16px;">
            <div style="font-size:0.75rem;color:#94a3b8;font-weight:600;text-transform:uppercase;letter-spacing:.6px;margin-bottom:8px;">Add Contacts</div>
            <div style="display:flex;gap:8px;">
              <input id="proj-search" placeholder="Search by name or company..." oninput="renderProjectContactPicker(${p.id})"
                     style="flex:1;padding:9px 12px;border-radius:6px;border:1px solid #334155;background:#0f172a;color:#f1f5f9;font-size:0.85rem;outline:none;">
            </div>
            <div id="proj-picker" style="max-height:180px;overflow-y:auto;margin-top:8px;"></div>
          </div>

          <hr style="border:0;border-top:1px solid #334155;margin:16px 0;">

          <div style="font-size:0.75rem;color:#94a3b8;font-weight:600;text-transform:uppercase;letter-spacing:.6px;margin-bottom:10px;">Contacts in Project</div>
          <div id="project-contact-list">${rows}</div>

          <div style="margin-top:20px;display:flex;gap:10px;justify-content:flex-end;">
            <button onclick="if(confirm('Delete project ${escHtml(p.name)}?')){deleteProject(${p.id});closeProjectDetail();openProjectsPanel();}"
                    style="padding:8px 16px;border-radius:6px;border:1px solid #334155;background:none;color:#ef4444;font-size:0.82rem;cursor:pointer;">Delete Project</button>
          </div>
        </div>`;
    }

    function refreshProjectDetail(projectId) {
        closeProjectDetail();
        openProjectDetail(projectId);
    }

    function renderProjectContactPicker(projectId) {
        const q = (document.getElementById('proj-search').value||'').toLowerCase().trim();
        const p = getProject(projectId);
        if (!p) return;
        const picker = document.getElementById('proj-picker');
        if (!q) { picker.innerHTML = ''; return; }
        const matches = contacts.filter(c =>
            !p.contactIds.includes(c.id) &&
            (c.person.toLowerCase().includes(q) || c.entity.toLowerCase().includes(q))
        ).slice(0,10);
        if (!matches.length) {
            picker.innerHTML = '<div style="color:#64748b;font-size:0.8rem;padding:8px;">No matches</div>';
            return;
        }
        picker.innerHTML = matches.map(c => `
            <div onclick="addContactToProject(${projectId},${c.id});refreshProjectDetail(${projectId});"
                 style="padding:8px 12px;border-radius:6px;background:#0f172a;border:1px solid #334155;margin-bottom:4px;cursor:pointer;font-size:0.85rem;color:#f1f5f9;">
              <strong>${escHtml(c.person)}</strong>
              <span style="color:#64748b;font-size:0.78rem;margin-left:6px;">${escHtml(c.entity)}</span>
            </div>`).join('');
    }

    // ── State
    let currentData = contacts;
    let currentPage = 0;
    const PAGE_SIZE  = 100;

    // ── Search
    function filter() {
        const q = document.getElementById('search').value.toLowerCase().trim();
        if (!q) { currentData = contacts; }
        else {
            currentData = contacts.filter(c =>
                c.person.toLowerCase().includes(q)   ||
                c.entity.toLowerCase().includes(q)   ||
                c.position.toLowerCase().includes(q) ||
                c.sector_tags.toLowerCase().includes(q) ||
                c.email.toLowerCase().includes(q)    ||
                c.notes.join(' ').toLowerCase().includes(q)
            );
        }
        currentPage = 0;
        renderList();
        document.getElementById('stats').textContent =
            currentData.length === contacts.length
                ? contacts.length.toLocaleString() + ' contacts'
                : currentData.length.toLocaleString() + ' / ' + contacts.length.toLocaleString();
    }

    // ── Sidebar list
    function renderList() {
        const slice  = currentData.slice(0, (currentPage + 1) * PAGE_SIZE);
        const listEl = document.getElementById('list');
        listEl.innerHTML = slice.map(c => `
            <div class="contact-item" onclick="view(${c.id})" style="padding:12px 15px;position:relative;">
                <strong style="font-size:0.9rem;display:block;padding-right:28px;">${c.person}</strong>
                <span style="color:#64748b;font-size:0.8rem;">${c.entity}</span>
                ${c.position ? `<br><span style="color:#475569;font-size:0.75rem;">${c.position}</span>` : ''}
                ${c.status === 'Contacted'
                    ? `<span style="position:absolute;top:12px;right:10px;background:#1d4ed8;color:#bfdbfe;
                        font-size:0.6rem;padding:2px 6px;border-radius:8px;">✓</span>`
                    : ''}
            </div>`).join('');
        if (slice.length < currentData.length) {
            listEl.innerHTML += `
                <div onclick="currentPage++;renderList();"
                     style="padding:12px;text-align:center;color:#3b82f6;cursor:pointer;font-size:0.82rem;
                            border-top:1px solid #334155;">
                    Load more (${currentData.length - slice.length} remaining)
                </div>`;
        }
    }

    // ── Detail panel
    function view(id) {
        const c = contacts.find(x => x.id == id);
        if (!c) return;

        // Score colour
        const score = c.relevance_score;
        const scoreColor = score >= 7 ? '#22c55e' : score >= 4 ? '#f59e0b' : '#94a3b8';

        // Helper: labelled pill
        const pill = (label, val, href) => {
            if (!val) return '';
            const inner = href
                ? `<a href="${href}" target="_blank" style="color:inherit;text-decoration:none;">${val}</a>`
                : val;
            return `<div class="cp-pill"><span class="cp-label">${label}</span>${inner}</div>`;
        };

        // Contact points block
        const cpRows = [
            pill('LinkedIn',  c.linkedin  ? 'View Profile →' : '', c.linkedin),
            pill('Email',     c.email,    `mailto:${c.email}`),
            pill('Email 2',   c.email2,   `mailto:${c.email2}`),
            pill('Email 3',   c.email3,   `mailto:${c.email3}`),
            pill('Phone',     c.phone,    `tel:${c.phone}`),
            pill('WhatsApp',  c.whatsapp, `https://wa.me/${c.whatsapp.replace(/\D/g,'')}`),
            pill('Telegram',  c.telegram, c.telegram.startsWith('@') ? `https://t.me/${c.telegram.slice(1)}` : `https://t.me/${c.telegram}`),
            pill('Signal',    c.signal,   ''),
            pill('WeChat',    c.wechat,   ''),
            pill('Twitter/X', c.twitter,  `https://twitter.com/${c.twitter.replace('@','')}`),
            pill('Website',   c.website1, c.website1.startsWith('http') ? c.website1 : 'https://'+c.website1),
            pill('Website 2', c.website2, c.website2.startsWith('http') ? c.website2 : 'https://'+c.website2),
            pill('Website 3', c.website3, c.website3.startsWith('http') ? c.website3 : 'https://'+c.website3),
        ].filter(Boolean).join('');

        const cpBlock = cpRows
            ? `<section class="detail-section">
                <div class="section-label">Contact Points</div>
                <div class="cp-grid">${cpRows}</div>
               </section>`
            : `<section class="detail-section">
                <div class="section-label">Contact Points</div>
                <p style="color:#475569;font-size:0.85rem;">No contact details on file.</p>
               </section>`;

        // About block (LinkedIn About — populated via LOCAL_BRIDGE)
        const aboutBlock = `
            <section class="detail-section">
                <div class="section-label">About <span style="color:#475569;font-size:0.7rem;font-weight:400;">(LinkedIn)</span></div>
                ${c.about
                    ? `<p style="line-height:1.8;color:#cbd5e1;white-space:pre-wrap;">${c.about}</p>`
                    : `<p style="color:#475569;font-size:0.85rem;">No About text imported yet. Use the AI Import button to fetch from LinkedIn.</p>`}
            </section>`;

        // Message history
        const notesBlock = c.notes.length
            ? c.notes.map(n => `
                <div style="background:#1e293b;border-left:3px solid #3b82f6;border-radius:4px;
                            padding:12px 16px;margin:8px 0;line-height:1.7;color:#cbd5e1;
                            font-size:0.85rem;white-space:pre-wrap;">${n}</div>`).join('')
            : `<p style="color:#475569;font-size:0.85rem;">No message history.</p>`;

        // Tags
        const tagsHtml = [c.sector_tags, c.custom_tags].filter(Boolean)
            .flatMap(t => t.split(',').map(s => s.trim()).filter(Boolean))
            .map(t => `<span style="background:#1e3a5f;color:#93c5fd;padding:3px 10px;
                                    border-radius:12px;font-size:0.72rem;">${t}</span>`)
            .join(' ');

        document.getElementById('detail').innerHTML = `
            <style>
                .detail-section { margin-bottom:24px; }
                .section-label  { color:#64748b;font-size:0.7rem;text-transform:uppercase;
                                  letter-spacing:1.2px;font-weight:600;margin-bottom:10px; }
                .cp-grid        { display:flex;flex-wrap:wrap;gap:8px; }
                .cp-pill        { background:#1e293b;border:1px solid #334155;border-radius:6px;
                                  padding:6px 12px;font-size:0.82rem;color:#e2e8f0; }
                .cp-label       { color:#64748b;font-size:0.7rem;display:block;margin-bottom:2px; }
                .cp-pill a      { color:#3b82f6; }
                .cp-pill a:hover{ text-decoration:underline; }
            </style>

            <!-- Header -->
            <div style="display:flex;justify-content:space-between;align-items:flex-start;
                        flex-wrap:wrap;gap:16px;margin-bottom:20px;">
                <div style="flex:1;min-width:200px;">
                    <h1 style="margin:0 0 4px;font-size:1.5rem;">${c.person}</h1>
                    <p  style="color:var(--accent);font-size:1rem;margin:0 0 2px;">${c.position}</p>
                    <p  style="color:#94a3b8;font-size:0.9rem;margin:0;">${c.entity}</p>
                    ${tagsHtml ? `<div style="margin-top:10px;display:flex;flex-wrap:wrap;gap:6px;">${tagsHtml}</div>` : ''}
                </div>
                <div style="text-align:right;flex-shrink:0;">
                    <div style="font-size:2rem;font-weight:700;color:${scoreColor};">
                        ${score}<span style="font-size:0.8rem;color:#64748b;">/12</span>
                    </div>
                    <div style="font-size:0.65rem;color:#64748b;margin-bottom:8px;">RELEVANCE</div>
                    <span style="background:${c.status==='Contacted'?'#1d4ed8':'#334155'};
                                 color:${c.status==='Contacted'?'#bfdbfe':'#94a3b8'};
                                 padding:3px 10px;border-radius:10px;font-size:0.72rem;">${c.status}</span>
                    &nbsp;
                    <span style="background:#1e3a2f;color:#86efac;padding:3px 10px;
                                 border-radius:10px;font-size:0.72rem;">${c.priority}</span>
                    <div style="margin-top:10px;">
                        <button onclick="showAddToProjectMenu(${c.id}, this)" style="padding:6px 14px;border-radius:6px;border:1px solid #334155;background:#1e293b;color:#94a3b8;font-size:0.8rem;cursor:pointer;">📁 Add to Project</button>
                    </div>
                </div>
            </div>

            <!-- Meta grid -->
            <section class="detail-section">
                <div class="section-label">Profile</div>
                <div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(160px,1fr));gap:12px;">
                    ${c.connected_on ? `<div><div class="section-label">Connected</div><div style="color:#e2e8f0;font-size:0.88rem;">${c.connected_on}</div></div>` : ''}
                    ${c.seniority    ? `<div><div class="section-label">Seniority</div><div style="color:#e2e8f0;font-size:0.88rem;">${c.seniority}</div></div>` : ''}
                    ${c.birthday     ? `<div><div class="section-label">Birthday</div><div style="color:#e2e8f0;font-size:0.88rem;">${c.birthday}</div></div>` : ''}
                </div>
            </section>

            ${cpBlock}
            ${aboutBlock}

            <!-- Message history -->
            <section class="detail-section">
                <div class="section-label">Message History</div>
                ${notesBlock}
            </section>
        `;
    }


    // ══════════════════════════════════════════════════════
    //  ADD CONTACT MODAL — STATE & HELPERS
    // ══════════════════════════════════════════════════════
    let _imgBase64 = null;   // current screenshot as base64

    function openAddModal()  { document.getElementById('addModal').classList.add('open'); }
    function closeAddModal() {
        document.getElementById('addModal').classList.remove('open');
        clearAddForm();
    }

    function clearAddForm() {
        const ids = ['f_first_name','f_last_name','f_company','f_position',
                     'f_linkedin_url','f_about','f_email','f_phone',
                     'f_whatsapp','f_telegram','f_twitter','f_website1',
                     'f_sector_tags','f_relevance_score','f_notes','liUrl'];
        ids.forEach(id => { const el = document.getElementById(id); if(el) el.value=''; });
        ['f_seniority','f_priority','f_status'].forEach(id => {
            const el = document.getElementById(id); if(el) el.selectedIndex=0;
        });
        document.getElementById('f_connected_on').value = '';
        setStatus('','');
        clearImage();
        document.getElementById('confidenceWrap').style.display='none';
        // Reset JSON tab fields
        const jp = document.getElementById('jsonPasteArea');
        if (jp) jp.value = '';
        const js = document.getElementById('jsonStatus');
        if (js) js.textContent = '';
        const sf = document.getElementById('sharedForm');
        if (sf) sf.style.display = 'none';
        const sb = document.getElementById('saveBtn');
        if (sb) sb.style.display = 'none';
        const fm = document.getElementById('formReadyMsg');
        if (fm) fm.textContent = '';
        switchTab('json');
    }

    function clearImage() {
        _imgBase64 = null;
        document.getElementById('imgPreviewWrap').style.display='none';
        document.getElementById('imgPreview').src='';
        document.getElementById('imgInput').value='';
        document.getElementById('dropZone').style.display='block';
    }

    function dzDrag(e, over) {
        e.preventDefault();
        document.getElementById('dropZone').classList.toggle('drag-over', over);
    }

    function dzDrop(e) {
        e.preventDefault();
        dzDrag(e, false);
        const file = e.dataTransfer.files[0];
        if (file && file.type.startsWith('image/')) handleImage(file);
    }

    let _imgMediaType = 'image/jpeg';
    function handleImage(file) {
        if (!file) return;
        _imgMediaType = file.type || 'image/jpeg';
        const reader = new FileReader();
        reader.onload = ev => {
            const dataUrl = ev.target.result;
            _imgBase64 = dataUrl.split(',')[1];
            document.getElementById('imgPreview').src = dataUrl;
            document.getElementById('imgPreviewWrap').style.display='block';
            document.getElementById('dropZone').style.display='none';
            setStatus('loading', '🧠 Screenshot detected — click ⚡ Extract to analyse with AI...');
        };
        reader.readAsDataURL(file);
    }

    function setStatus(type, msg) {
        const el = document.getElementById('aiStatus');
        el.className = 'ai-status' + (type ? ' '+type : '');
        el.textContent = msg;
    }

    // ══════════════════════════════════════════════════════
    //  AI EXTRACTION — SCREENSHOT PATH (Claude Vision)
    // ══════════════════════════════════════════════════════
    // ── API key helpers
    function getApiKey() {
        return localStorage.getItem('cgs_anthropic_key') || '';
    }
    function saveApiKey(val) {
        val = val.trim();
        if (val) {
            localStorage.setItem('cgs_anthropic_key', val);
            const inp = document.getElementById('apiKeyInput');
            const st  = document.getElementById('keyStatus');
            inp.classList.add('saved');
            st.textContent = '✓ Saved';
            st.style.color = '#22c55e';
            setTimeout(() => { inp.classList.remove('saved'); st.textContent=''; }, 2000);
        }
    }
    function toggleKeyVisible() {
        const inp = document.getElementById('apiKeyInput');
        const tog = document.getElementById('keyToggle');
        if (inp.type === 'password') { inp.type='text'; tog.textContent='Hide'; }
        else { inp.type='password'; tog.textContent='Show'; }
    }
    function buildHeaders() {
        const key = getApiKey();
        return {
            'Content-Type': 'application/json',
            'x-api-key': key,
            'anthropic-version': '2023-06-01',
            'anthropic-dangerous-direct-browser-access': 'true'
        };
    }
    function checkApiKey() {
        const key = getApiKey();
        if (!key) {
            setStatus('err', '⚠ No API key set — enter your Anthropic key in the bar above first.');
            document.getElementById('apiKeyInput').focus();
            return false;
        }
        return true;
    }

    async function extractFromScreenshot() {
        if (!_imgBase64) return false;
        if (!checkApiKey()) return false;
        setStatus('loading','🔍 Analysing screenshot with AI...');

        const prompt = `You are extracting LinkedIn profile data from a screenshot.
Return ONLY valid JSON, no markdown, no explanation. Use this exact schema:
{
  "first_name": "",
  "last_name": "",
  "full_name": "",
  "company": "",
  "position": "",
  "linkedin_url": "",
  "about": "",
  "email": "",
  "phone": "",
  "whatsapp": "",
  "telegram": "",
  "twitter": "",
  "website1": "",
  "website2": "",
  "sector_tags": [],
  "seniority": "",
  "confidence": 0
}
Rules:
- confidence = integer 0-100 reflecting how complete the extraction is
- sector_tags = array of relevant industry tags you infer (e.g. ["DeFi","Web3","AI"])
- seniority = one of: C-Suite/SVP | Senior Executive/Founder | Manager/Senior | Individual Contributor | Student/Entry
- Extract every visible field. If not visible, leave empty string or empty array.
- linkedin_url: extract from the page URL bar if visible, or infer from visible username
- about: the full "About" section text if visible`;

        try {
            const resp = await fetch('https://api.anthropic.com/v1/messages', {
                method: 'POST',
                headers: buildHeaders(),
                body: JSON.stringify({
                    model: 'claude-sonnet-4-20250514',
                    max_tokens: 1000,
                    messages: [{
                        role: 'user',
                        content: [
                            { type: 'image', source: { type: 'base64',
                              media_type: _imgMediaType, data: _imgBase64 }},
                            { type: 'text', text: prompt }
                        ]
                    }]
                })
            });
            const data = await resp.json();
            const raw = data.content?.find(b => b.type==='text')?.text || '';
            const parsed = JSON.parse(raw.replace(/```json|```/g,'').trim());
            populateForm(parsed);
            return true;
        } catch(err) {
            setStatus('err','⚠ Vision extraction failed: ' + err.message);
            return false;
        }
    }

    // ══════════════════════════════════════════════════════
    //  AI EXTRACTION — URL PATH (LOCAL_BRIDGE + Claude fallback)
    // ══════════════════════════════════════════════════════
    async function extractFromUrl() {
        const url = document.getElementById('liUrl').value.trim();
        const btn  = document.getElementById('extractBtn');
        btn.disabled = true;

        // Gate on API key
        if (!checkApiKey()) { btn.disabled = false; return; }

        // If there's a screenshot, use that
        if (_imgBase64) {
            const ok = await extractFromScreenshot();
            btn.disabled = false;
            return;
        }

        if (!url) {
            setStatus('err','⚠ Paste a LinkedIn URL or drop a screenshot first.');
            btn.disabled = false;
            return;
        }

        // ── Path 1: Try LOCAL_BRIDGE (Selenium running locally on port 5000)
        setStatus('loading','⚡ Trying LOCAL_BRIDGE on port 5000...');
        try {
            const bridgeResp = await fetch('http://127.0.0.1:5000/import', {
                method: 'POST',
                headers: {'Content-Type':'application/json'},
                body: JSON.stringify({ url }),
                signal: AbortSignal.timeout(8000)
            });
            if (bridgeResp.ok) {
                const bridgeData = await bridgeResp.json();
                if (bridgeData && (bridgeData.first_name || bridgeData.full_name)) {
                    populateForm(bridgeData);
                    setStatus('ok','✓ Populated via LOCAL_BRIDGE (live LinkedIn scrape)');
                    btn.disabled = false;
                    return;
                }
            }
        } catch(_) {
            // Bridge not running — fall through to AI path
        }

        // ── Path 2: AI inference from URL metadata alone
        setStatus('loading','🧠 LOCAL_BRIDGE offline — extracting from URL with AI...');
        try {
            const username = url.split('/in/')[1]?.replace(/\//g,'') || '';
            const prompt = `A user wants to add a LinkedIn contact. The profile URL is: ${url}
The LinkedIn username/slug is: ${username}

From the URL slug alone, infer what you can and return ONLY valid JSON using this schema:
{
  "first_name": "",
  "last_name": "",
  "full_name": "",
  "company": "",
  "position": "",
  "linkedin_url": "${url}",
  "about": "",
  "email": "",
  "phone": "",
  "sector_tags": [],
  "seniority": "",
  "confidence": 0
}
Set confidence low (10-25) since you only have the URL. Infer name from the slug if possible (e.g. "john-smith-abc123" → first: John, last: Smith). Leave company/position/about empty.`;

            const resp = await fetch('https://api.anthropic.com/v1/messages', {
                method: 'POST',
                headers: buildHeaders(),
                body: JSON.stringify({
                    model: 'claude-sonnet-4-20250514',
                    max_tokens: 500,
                    messages: [{ role: 'user', content: prompt }]
                })
            });
            const data = await resp.json();
            const raw = data.content?.find(b => b.type==='text')?.text || '';
            const parsed = JSON.parse(raw.replace(/```json|```/g,'').trim());
            populateForm(parsed);
            setStatus('ok','✓ Basic info extracted from URL. Drop a screenshot for full profile data.');
        } catch(err) {
            setStatus('err','⚠ Extraction failed: ' + err.message);
        }
        btn.disabled = false;
    }

    // ══════════════════════════════════════════════════════
    //  POPULATE FORM FROM EXTRACTED DATA
    // ══════════════════════════════════════════════════════
    function populateForm(d) {
        const set = (id, val) => {
            const el = document.getElementById(id);
            if (!el || val === undefined || val === null) return;
            const str = Array.isArray(val) ? val.join(', ') : String(val);
            if (!str) return;
            el.value = str;
            el.classList.add('field-populated');
            setTimeout(() => el.classList.remove('field-populated'), 2500);
        };

        set('f_first_name',     d.first_name);
        set('f_last_name',      d.last_name);
        set('f_company',        d.company);
        set('f_position',       d.position);
        set('f_linkedin_url',   d.linkedin_url || document.getElementById('liUrl').value);
        set('f_about',          d.about);
        set('f_email',          d.email);
        set('f_phone',          d.phone);
        set('f_whatsapp',       d.whatsapp);
        set('f_telegram',       d.telegram);
        set('f_twitter',        d.twitter);
        set('f_website1',       d.website1);
        set('f_sector_tags',    d.sector_tags);

        // Seniority select
        if (d.seniority) {
            const sel = document.getElementById('f_seniority');
            [...sel.options].forEach(o => { if(o.value===d.seniority) sel.value=d.seniority; });
        }

        // Auto-assign relevance & priority from seniority
        if (d.seniority && !d.relevance_score) {
            const scoreMap = {
                'C-Suite/SVP': 8, 'Senior Executive/Founder': 7,
                'Manager/Senior': 5, 'Individual Contributor': 3, 'Student/Entry': 1
            };
            const score = scoreMap[d.seniority] || 3;
            document.getElementById('f_relevance_score').value = score;
        } else if (d.relevance_score) {
            set('f_relevance_score', d.relevance_score);
        }

        // Confidence bar
        if (d.confidence != null) {
            const pct = Math.min(100, Math.max(0, d.confidence));
            document.getElementById('confidenceWrap').style.display='block';
            document.getElementById('confidencePct').textContent = pct + '%';
            document.getElementById('confidenceFill').style.width = pct + '%';
            const msg = pct >= 70
                ? `✓ High confidence extraction (${pct}%) — review and save`
                : pct >= 35
                    ? `⚠ Partial extraction (${pct}%) — please fill missing fields`
                    : `⚠ Low confidence (${pct}%) — drop a screenshot for better results`;
            setStatus(pct>=70?'ok':pct>=35?'loading':'err', msg);
        }
    }

    // ══════════════════════════════════════════════════════
    //  SAVE NEW CONTACT TO IN-MEMORY LIST
    // ══════════════════════════════════════════════════════
    function saveNewContact() {
        const g = id => document.getElementById(id)?.value?.trim() || '';
        const firstName = g('f_first_name');
        const lastName  = g('f_last_name');
        const fullName  = (firstName + ' ' + lastName).trim();

        if (!fullName || fullName === '') {
            setStatus('err','⚠ First Name or Last Name is required.');
            return;
        }

        const newId = contacts.reduce((mx,c) => Math.max(mx, c.id||0), 0) + 1;
        const today = new Date().toISOString().split('T')[0];

        const newContact = {
            id:              newId,
            person:          fullName,
            entity:          g('f_company'),
            position:        g('f_position'),
            linkedin:        g('f_linkedin_url'),
            about:           g('f_about'),
            email:           g('f_email'),
            email2:          '',
            email3:          '',
            phone:           g('f_phone'),
            whatsapp:        g('f_whatsapp'),
            telegram:        g('f_telegram'),
            signal:          '',
            wechat:          '',
            twitter:         g('f_twitter'),
            website1:        g('f_website1'),
            website2:        '',
            website3:        '',
            birthday:        '',
            connected_on:    g('f_connected_on') || today,
            sector_tags:     g('f_sector_tags'),
            custom_tags:     '',
            seniority:       g('f_seniority'),
            relevance_score: parseInt(g('f_relevance_score')) || 0,
            priority:        g('f_priority') || 'Medium',
            status:          g('f_status') || 'Not contacted',
            notes:           g('f_notes') ? [g('f_notes')] : []
        };

        // Prepend to contacts array so it appears first in list
        contacts.unshift(newContact);
        persistNewContact(newContact);
        currentData = contacts;
        renderList();
        document.getElementById('stats').textContent = contacts.length.toLocaleString() + ' contacts';

        closeAddModal();

        // Auto-open the new contact in detail view
        setTimeout(() => view(newId), 150);

        // Exportable JSON reminder
        console.info('New contact saved to memory. Export JSON to persist:', JSON.stringify(newContact, null, 2));
    }

    // ══════════════════════════════════════════════════════
    //  EXPORT UPDATED JSON — full dataset download
    // ══════════════════════════════════════════════════════
    function exportJSON() {
        // Reconstruct window.INITIAL_DATA-compatible records from in-memory contacts
        const exportContacts = contacts.map(c => ({
            id:              c.id,
            first_name:      c.person ? c.person.split(' ')[0] : '',
            last_name:       c.person ? c.person.split(' ').slice(1).join(' ') : '',
            full_name:       c.person || '',
            company:         c.entity || '',
            position:        c.position || '',
            linkedin_url:    c.linkedin || '',
            about:           c.about || '',
            email:           c.email || '',
            email2:          c.email2 || '',
            email3:          c.email3 || '',
            connected_on:    c.connected_on || '',
            sector_tags:     c.sector_tags ? c.sector_tags.split(',').map(s=>s.trim()).filter(Boolean) : [],
            seniority:       c.seniority || '',
            relevance_score: c.relevance_score || 0,
            priority:        c.priority || '',
            has_email:       c.email ? 1 : 0,
            status:          c.status || 'Not contacted',
            whatsapp:        c.whatsapp || '',
            telegram:        c.telegram || '',
            signal:          c.signal || '',
            wechat:          c.wechat || '',
            custom_tags:     c.custom_tags ? c.custom_tags.split(',').map(s=>s.trim()).filter(Boolean) : [],
            projects:        [],
            notes:           c.notes && c.notes.length
                                ? c.notes.map((t,i) => ({date: c.connected_on || '', text: t}))
                                : [],
            twitter:         c.twitter || '',
            website1:        c.website1 || '',
            website2:        c.website2 || '',
            website3:        c.website3 || '',
            phone:           c.phone || '',
            birthday:        c.birthday || ''
        }));

        const payload = { contacts: exportContacts, projects: {} };
        const blob = new Blob([JSON.stringify(payload, null, 2)], {type: 'application/json'});
        const url  = URL.createObjectURL(blob);
        const ts   = new Date().toISOString().split('T')[0];
        const a    = document.createElement('a');
        a.href     = url;
        a.download = `CGS_Network_${ts}.json`;
        a.click();
        URL.revokeObjectURL(url);

        // Toast notification
        const toast = document.createElement('div');
        toast.textContent = `✓ Exported ${exportContacts.length.toLocaleString()} contacts → CGS_Network_${ts}.json`;
        toast.style.cssText = `position:fixed;bottom:24px;right:24px;background:#1e293b;
            border:1px solid #22c55e;color:#86efac;padding:12px 20px;border-radius:8px;
            font-size:0.82rem;z-index:9999;box-shadow:0 8px 24px rgba(0,0,0,.4);`;
        document.body.appendChild(toast);
        setTimeout(() => toast.remove(), 4000);
    }

    // ══════════════════════════════════════════════════════
    //  TAB SWITCHING
    // ══════════════════════════════════════════════════════
    function switchTab(tab) {
        ['json','manual','ai'].forEach(t => {
            document.getElementById('panel-'+t).style.display = t===tab ? 'block' : 'none';
            const btn = document.getElementById('tab-'+t);
            btn.style.background = t===tab ? '#3b82f6' : '#1e293b';
            btn.style.color      = t===tab ? '#fff'    : '#64748b';
        });
        // Manual tab: show form immediately
        if (tab === 'manual') {
            document.getElementById('sharedForm').style.display = 'block';
            document.getElementById('saveBtn').style.display    = 'block';
            document.getElementById('formReadyMsg').textContent = '';
        }
    }

    // ══════════════════════════════════════════════════════
    //  COPY PROMPT TO CLIPBOARD
    // ══════════════════════════════════════════════════════
    function copyPrompt() {
        const txt = document.getElementById('promptText').textContent;
        navigator.clipboard.writeText(txt).then(() => {
            const btn = document.getElementById('copyBtn');
            btn.textContent = '✓ Copied!';
            btn.style.color = '#22c55e';
            setTimeout(() => { btn.textContent='Copy'; btn.style.color='#94a3b8'; }, 2000);
        });
    }

    // ══════════════════════════════════════════════════════
    //  VALIDATE JSON PASTE
    // ══════════════════════════════════════════════════════
    function validateJsonPaste(val) {
        const el = document.getElementById('jsonStatus');
        if (!val.trim()) { el.textContent=''; return; }
        try {
            const d = JSON.parse(val.replace(/```json|```/g,'').trim());
            const name = d.full_name || ((d.first_name||'') + ' ' + (d.last_name||'')).trim();
            el.style.color = '#22c55e';
            el.textContent = name
                ? '✓ Valid JSON — detected: ' + name + (d.company ? ' @ ' + d.company : '')
                : '✓ Valid JSON — check name fields';
        } catch(e) {
            el.style.color = '#ef4444';
            el.textContent = '✗ Invalid JSON — copy exactly what Claude returned';
        }
    }

    // ══════════════════════════════════════════════════════
    //  IMPORT FROM PASTED JSON
    // ══════════════════════════════════════════════════════
    function importFromJson() {
        const raw = document.getElementById('jsonPasteArea').value.trim();
        if (!raw) {
            document.getElementById('jsonStatus').textContent = '⚠ Nothing pasted yet.';
            document.getElementById('jsonStatus').style.color = '#f59e0b';
            return;
        }
        let d;
        try {
            d = JSON.parse(raw.replace(/```json|```/g,'').trim());
        } catch(e) {
            document.getElementById('jsonStatus').textContent = "✗ Cannot parse — paste Claude's exact JSON output.";
            document.getElementById('jsonStatus').style.color = '#ef4444';
            return;
        }
        populateForm(d);
        document.getElementById('sharedForm').style.display = 'block';
        document.getElementById('saveBtn').style.display    = 'block';
        const name = d.full_name || ((d.first_name||'') + ' ' + (d.last_name||'')).trim();
        document.getElementById('formReadyMsg').textContent =
            '✓ ' + (name||'Contact') + ' imported — review fields below then hit Save';
        // Scroll form into view
        document.getElementById('sharedForm').scrollIntoView({behavior:'smooth', block:'start'});
    }

    // ── Init
    // Load saved API key from localStorage
    (function() {
        const saved = localStorage.getItem('cgs_anthropic_key');
        if (saved) {
            const inp = document.getElementById('apiKeyInput');
            if (inp) inp.value = saved;
            const st = document.getElementById('keyStatus');
            if (st) { st.textContent = '✓ Key loaded'; st.style.color='#22c55e'; }
        }
    })();

    renderList();
    document.getElementById('stats').textContent = contacts.length.toLocaleString() + ' contacts';


function showAddContactModal(){
  var ex=document.getElementById("add-contact-modal");if(ex)ex.remove();
  var ov=document.createElement("div");ov.id="add-contact-modal";
  ov.style.cssText="position:fixed;inset:0;background:rgba(0,0,0,0.7);z-index:9999;display:flex;align-items:center;justify-content:center;padding:1rem;overflow-y:auto;";
  var h='<div style="background:#1a1d27;border:1px solid #2d3144;border-radius:14px;width:100%;max-width:580px;padding:1.75rem;color:#e8e8e8;font-family:-apple-system,sans-serif;position:relative;margin:auto;">';
  h+='<button onclick="document.getElementById(\'add-contact-modal\').remove()" style="position:absolute;top:1rem;right:1rem;background:none;border:none;color:#666;font-size:1.3rem;cursor:pointer;">&#x2715;</button>';
  h+='<h3 style="font-size:1rem;font-weight:600;margin-bottom:0.25rem;">Add new contact</h3>';
  h+='<p style="font-size:0.75rem;color:#666;margin-bottom:1rem;">Paste a LinkedIn URL and click AI Extract, or fill manually.</p>';
  h+='<div style="display:flex;gap:8px;margin-bottom:0.5rem;"><input id="nc-url" type="text" placeholder="https://linkedin.com/in/..." style="flex:1;background:#0f1117;border:1px solid #2d3144;border-radius:8px;color:#e8e8e8;font-size:0.82rem;padding:0.55rem 0.85rem;outline:none;"><button onclick="ncExtract()" id="nc-xbtn" style="padding:0.55rem 1rem;border-radius:8px;background:#1e3a6e;color:#7ab3f7;border:1px solid #2d5a9e;font-size:0.8rem;cursor:pointer;white-space:nowrap;font-weight:500;">AI Extract</button></div>';
  h+='<div id="nc-xst" style="display:none;font-size:0.75rem;padding:0.4rem 0.75rem;border-radius:6px;margin-bottom:0.75rem;"></div>';
  h+='<hr style="border:none;border-top:1px solid #1e2030;margin:0.75rem 0;">';
  h+='<div style="display:grid;grid-template-columns:1fr 1fr;gap:0.65rem;">';
  [["nc-fn","First name *"],["nc-ln","Last name *"],["nc-co","Company"],["nc-ti","Title"],["nc-em","Email"],["nc-ph","Phone"],["nc-wa","WhatsApp"],["nc-tw","Twitter"]].forEach(function(f){h+='<div><label style="font-size:0.7rem;color:#555;text-transform:uppercase;letter-spacing:0.06em;display:block;margin-bottom:3px;">'+f[1]+'</label><input id="'+f[0]+'" style="width:100%;background:#0f1117;border:1px solid #2d3144;border-radius:8px;color:#e8e8e8;font-size:0.82rem;padding:0.5rem 0.75rem;outline:none;"></div>';});
  h+='</div>';
  h+='<div style="margin-top:0.65rem;"><label style="font-size:0.7rem;color:#555;text-transform:uppercase;letter-spacing:0.06em;display:block;margin-bottom:3px;">LinkedIn URL</label><input id="nc-li" style="width:100%;background:#0f1117;border:1px solid #2d3144;border-radius:8px;color:#e8e8e8;font-size:0.82rem;padding:0.5rem 0.75rem;outline:none;"></div>';
  h+='<div style="margin-top:0.65rem;"><label style="font-size:0.7rem;color:#555;text-transform:uppercase;letter-spacing:0.06em;display:block;margin-bottom:3px;">Tags (comma separated)</label><input id="nc-tg" style="width:100%;background:#0f1117;border:1px solid #2d3144;border-radius:8px;color:#e8e8e8;font-size:0.82rem;padding:0.5rem 0.75rem;outline:none;"></div>';
  h+='<div style="margin-top:0.65rem;"><label style="font-size:0.7rem;color:#555;text-transform:uppercase;letter-spacing:0.06em;display:block;margin-bottom:3px;">Priority</label><select id="nc-pr" style="background:#0f1117;border:1px solid #2d3144;border-radius:8px;color:#e8e8e8;font-size:0.82rem;padding:0.5rem 0.75rem;outline:none;width:160px;"><option value="medium">Medium</option><option value="high">High</option><option value="low">Low</option></select></div>';
  h+='<div style="margin-top:0.65rem;"><label style="font-size:0.7rem;color:#555;text-transform:uppercase;letter-spacing:0.06em;display:block;margin-bottom:3px;">Note</label><textarea id="nc-no" style="width:100%;background:#0f1117;border:1px solid #2d3144;border-radius:8px;color:#e8e8e8;font-size:0.8rem;padding:0.5rem 0.75rem;resize:vertical;min-height:60px;outline:none;font-family:inherit;"></textarea></div>';
  h+='<div id="nc-err" style="display:none;color:#f87171;font-size:0.75rem;margin-top:0.4rem;"></div>';
  h+='<div style="display:flex;gap:8px;margin-top:1rem;justify-content:flex-end;"><button onclick="document.getElementById(\'add-contact-modal\').remove()" style="padding:0.5rem 1rem;border-radius:8px;background:none;border:1px solid #2d3144;color:#888;font-size:0.8rem;cursor:pointer;">Cancel</button><button onclick="ncSave()" style="padding:0.5rem 1.2rem;border-radius:8px;background:#16a34a;color:#fff;border:none;font-size:0.8rem;font-weight:500;cursor:pointer;">Save contact</button></div>';
  h+='</div>';ov.innerHTML=h;document.body.appendChild(ov);
}
async function ncExtract(){
  var url=(document.getElementById("nc-url")||{}).value||"";if(!url.trim())return;
  var btn=document.getElementById("nc-xbtn"),st=document.getElementById("nc-xst");
  if(btn){btn.disabled=true;btn.style.opacity="0.5";}
  if(st){st.style.cssText="display:block;background:#1a2030;color:#7a9fd4;border:1px solid #1e2d4a;font-size:0.75rem;padding:0.4rem 0.75rem;border-radius:6px;margin-bottom:0.75rem;";st.innerHTML='<span style="display:inline-block;width:9px;height:9px;border:2px solid #3d5a8a;border-top-color:#4a8cf7;border-radius:50%;animation:spin 0.7s linear infinite;vertical-align:middle;margin-right:6px;"></span>Calling Claude API...';}
  try{
    var r=await fetch("https://api.anthropic.com/v1/messages",{method:"POST",headers:{"Content-Type":"application/json","x-api-key":getApiKey(),"anthropic-version":"2023-06-01","anthropic-dangerous-direct-browser-access":"true"},body:JSON.stringify({model:"claude-sonnet-4-20250514",max_tokens:600,system:'Return ONLY valid JSON no markdown: {"first_name":"","last_name":"","title":"","company":"","email":"","phone":"","linkedin_url":"","twitter":"","tags":[],"priority":"High|Medium|Low","notes_summary":""}',messages:[{role:"user",content:"LinkedIn URL: "+url.trim()}]})});
    var d=await r.json();if(d.error)throw new Error(d.error.message);
    var p=JSON.parse(((d.content||[]).find(function(b){return b.type==="text";})||{}).text.replace(/```json|```/g,"").trim());
    var s=function(id,v){var el=document.getElementById(id);if(el&&v)el.value=v;};
    s("nc-fn",p.first_name);s("nc-ln",p.last_name);s("nc-co",p.company);s("nc-ti",p.title);
    s("nc-em",p.email);s("nc-ph",p.phone);s("nc-wa",p.phone);s("nc-tw",p.twitter);
    s("nc-li",p.linkedin_url||url.trim());s("nc-tg",(p.tags||[]).join(", "));
    if(p.priority){var sel=document.getElementById("nc-pr");if(sel)sel.value=p.priority.toLowerCase();}
    if(p.notes_summary){var no=document.getElementById("nc-no");if(no)no.value=p.notes_summary;}
    if(st){st.style.background="#141f14";st.style.color="#4ade80";st.style.borderColor="#1a3a1a";st.innerHTML="&#10003; Pre-filled. Review and save.";}
  }catch(e){if(st){st.style.background="#2a1414";st.style.color="#f87171";st.style.borderColor="#4a2020";st.innerHTML="AI failed: "+e.message;}}
  if(btn){btn.disabled=false;btn.style.opacity="1";}
}
function ncSave(){
  var fn=(document.getElementById("nc-fn").value||"").trim(),ln=(document.getElementById("nc-ln").value||"").trim();
  if(!fn||!ln){var e=document.getElementById("nc-err");e.style.display="block";e.textContent="First and last name required.";return;}
  var mid=contacts.reduce(function(a,c){return c.id>a?c.id:a;},0)+1;
  var tags=(document.getElementById("nc-tg").value||"").split(",").map(function(t){return t.trim();}).filter(Boolean);
  var note=(document.getElementById("nc-no").value||"").trim();
  var ts=new Date().toISOString().split('T')[0];
  // Build in internal mapped schema (same shape as contacts[])
  var nc={
    id:mid, person:fn+" "+ln, entity:(document.getElementById("nc-co").value||"").trim(),
    position:(document.getElementById("nc-ti").value||"").trim(),
    linkedin:(document.getElementById("nc-li").value||"").trim(),
    email:(document.getElementById("nc-em").value||"").trim(),
    email2:"",email3:"",phone:(document.getElementById("nc-ph").value||"").trim(),
    whatsapp:(document.getElementById("nc-wa").value||"").trim(),
    telegram:"",signal:"",wechat:"",twitter:(document.getElementById("nc-tw").value||"").trim(),
    website1:"",website2:"",website3:"",birthday:"",connected_on:ts,
    sector_tags:tags.join(", "),custom_tags:"",seniority:"",relevance_score:5,
    priority:(document.getElementById("nc-pr").value||"Medium"),
    status:"Not contacted",about:"",notes:note?[note]:[]
  };
  contacts.unshift(nc);
  persistNewContact(nc);
  currentData=contacts;
  if(typeof renderList==="function")renderList();
  document.getElementById('stats').textContent=contacts.length.toLocaleString()+' contacts';
  if(typeof showToast==="function")showToast("Contact "+nc.person+" added.");
  document.getElementById("add-contact-modal").remove();
  setTimeout(function(){view(mid);},200);
}

