#!/usr/bin/env python3
"""
Streaming splitter for CGS_FINAL_V8.html
Produces: index.html, app.js, data.js in C:\CGS\
"""
import re, sys, os

SRC  = r"C:\Marcus-Henri\CGS Contact Manager\CGS_FINAL_V8.html"
DEST = r"C:\CGS"

# Line numbers (1-based) from analysis:
#   1–146   : HTML shell (head + body open)
#   147     : <script>  ← replace with two <script src> tags
#   148     : // --- EMBEDDED DATA ---  ← skip
#   149     : const rawData = [...]     ← → data.js
#   150–977 : app JS logic              ← → app.js
#   978     : </script>                 ← skip
#   979–end : rest of HTML              ← → index.html (closing modal + body/html)

SCRIPT_OPEN_LINE   = 147
DATA_COMMENT_LINE  = 148
RAW_DATA_LINE      = 149
SCRIPT_CLOSE_LINE  = 978

html_path = os.path.join(DEST, "index.html")
app_path  = os.path.join(DEST, "app.js")
data_path = os.path.join(DEST, "data.js")

with (open(SRC,       "r", encoding="utf-8") as src,
      open(html_path, "w", encoding="utf-8") as fhtml,
      open(app_path,  "w", encoding="utf-8") as fapp,
      open(data_path, "w", encoding="utf-8") as fdata):

    # Write data.js header
    fdata.write("// Auto-generated by split.py — do not edit directly\n")
    # Write app.js header
    fapp.write("// Auto-generated by split.py — do not edit directly\n")
    fapp.write("// Depends on data.js being loaded first (window.INITIAL_DATA)\n\n")

    for lineno, line in enumerate(src, start=1):

        # ── HTML shell (pre-script) ──────────────────────────────────────
        if lineno < SCRIPT_OPEN_LINE:
            fhtml.write(line)

        # ── <script> opening tag → inject src references ─────────────────
        elif lineno == SCRIPT_OPEN_LINE:
            fhtml.write('    <script src="data.js"></script>\n')
            fhtml.write('    <script src="app.js" defer></script>\n')

        # ── Skip the embedded-data comment ───────────────────────────────
        elif lineno == DATA_COMMENT_LINE:
            pass  # drop the // --- EMBEDDED DATA --- comment

        # ── The giant rawData line → data.js ─────────────────────────────
        elif lineno == RAW_DATA_LINE:
            # Replace "const rawData = " with "window.INITIAL_DATA = "
            transformed = line.replace("const rawData = ", "window.INITIAL_DATA = ", 1)
            fdata.write(transformed)

        # ── App JS (lines 150..977) → app.js ─────────────────────────────
        elif lineno < SCRIPT_CLOSE_LINE:
            # Replace every reference to rawData with window.INITIAL_DATA
            out = re.sub(r'\brawData\b', 'window.INITIAL_DATA', line)
            fapp.write(out)

        # ── </script> closing tag → skip ──────────────────────────────────
        elif lineno == SCRIPT_CLOSE_LINE:
            pass  # already handled by src= tags above

        # ── Rest of HTML (modal markup + </body></html>) → index.html ────
        else:
            fhtml.write(line)

print("Done.")
print(f"  {html_path}")
print(f"  {app_path}")
print(f"  {data_path}")
